[package]
name = "dell-switcher-linux"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
tray-item = "0.7.0" 
gtk = "0.15"
hotkey = "0.3.1"
ddcci = "0.1.0"
